USE gestion;

CREATE TABLE IF NOT EXISTS cliente (
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  activo BOOLEAN DEFAULT false
) ENGINE=InnoDB DEFAULT CHARSET=utf8;